### ISSUE TITLE
Permission to Publish

### ISSUE THREAD

**Issue by jonstorer** [vesln/seed-forge#5]
@vesln whenever you get a chance

[~/src/seed-forge-upstream]$ npm publish
npm http PUT https://registry.npmjs.org/seed-forge
npm http 403 https://registry.npmjs.org/seed-forge
npm ERR! publish Failed PUT 403
npm ERR! Error: forbidden user: yonafin not authorized to modify seed-forge

**Comment by jonstorer** [comment]
@vesln ping

**Comment by vesln** [comment]
done
